import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import LenisScrollWrapper from "./components/Global/LenisScrollWrapper";
import { ThemeProvider } from "next-themes";
import Footer from "./components/Footer/Footer";
import { HoverProvider } from "./hooks/HoverContext";

export const neueMontreal = localFont({
  src: [
    {
      path: "./fonts/NeueMontreal/NeueMontreal-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/NeueMontreal/NeueMontreal-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/NeueMontreal/NeueMontreal-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/NeueMontreal/NeueMontreal-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-neue-montreal",
  display: "swap",
});

export const generalSans = localFont({
  src: [
    {
      path: "./fonts/GeneralSans/GeneralSans-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/GeneralSans/GeneralSans-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/GeneralSans/GeneralSans-Semibold.otf",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-general-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${generalSans.variable} ${neueMontreal.className} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system">
          <HoverProvider>
            <LenisScrollWrapper>{children}</LenisScrollWrapper>
          </HoverProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
