import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import LenisScrollWrapper from "./components/Global/LenisScrollWrapper";

export const neueMontreal = localFont({
  src: [
    {
      path: "./fonts/NeueMontreal/NeueMontreal-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/NeueMontreal/NeueMontreal-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/NeueMontreal/NeueMontreal-Light.otf",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-neue-montreal",
  display: "swap",
});

export const generalSans = localFont({
  src: [
    {
      path: "./fonts/GeneralSans/GeneralSans-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/GeneralSans/GeneralSans-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/GeneralSans/GeneralSans-Semibold.otf",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-general-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${generalSans.variable} ${neueMontreal.className} antialiased`}
      >
        <div className="bg-purple-600 h-1 w-10 fixed top-0 left-0 z-10000"></div>
        <div className="bg-purple-600 h-1 w-10 fixed top-1/4 -translate-y-1/2 left-0 z-10000"></div>
        <div className="bg-purple-600 h-1 w-10 fixed top-1/2 -translate-y-1/2 left-0 z-10000"></div>
        <div className="bg-purple-600 h-1 w-10 fixed top-3/4 -translate-y-1/2 left-0 z-10000"></div>
        <div className="bg-purple-600 h-1 w-10 fixed bottom-0 left-0 z-10000"></div>
        <LenisScrollWrapper>
          <Navbar />
          <main>{children}</main>
        </LenisScrollWrapper>
      </body>
    </html>
  );
}
